---

- name: Install from ppa | Install Dependencies | Update apt package cache
  apt: update_cache=yes
  sudo: yes

- name: Install from ppa | Install Dependencies | install apt dependencies
  apt: pkg=python-apt
  sudo: yes

- name: Install from ppa | Install Dependencies | add apt repository
  apt_repository: repo=ppa:git-core/ppa
  sudo: yes

- name: Install from ppa | Install Dependencies | Update apt package cache
  apt: update_cache=yes
  sudo: yes

- name: Install from ppa | Install git | apt package
  apt: pkg=git

- name: Install from source | Verify Installation | Check git version
  command: git --version
  register: result

- name: Install from PPA | Verify Installation | Fail if git version incorrect
  fail: msg="Wanted git version {{ git.version }}, got {{ result.stdout }} instead"
  when: "{{git.verify_version}} and '{{ git.version }}' not in result.stdout"

