---
- debug: var=git

- name: Verify Installation | Check current git version
  command: git --version
  ignore_errors: yes
  register: current_git_version

- include: do_install.yml
  when: current_git_version.failed or '{{ git.version }}' not in current_git_version.stdout

